### ISSUE TITLE
An error occurred with java. lang. NoClassDefFoundError

### ISSUE THREAD

**Issue by alylhb** [terl/lazysodium-java#127]
An error occurred with java. lang. NoClassDefFoundError: Failed resolution of: Lcom/goterl/resourceloader/SharedLibraryLoader;
Locate the code where the error occurred as LazySodiumJava (SodiumJava (LibraryLoader. Mode. BUNDLED_ONLY))

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/goterl/resourceloader/SharedLibraryLoader;
    	at com.goterl.lazysodium.utils.LibraryLoader.loadBundledLibrary(LibraryLoader.java:134)
    	at com.goterl.lazysodium.utils.LibraryLoader.loadLibrary(LibraryLoader.java:107)
    	at com.goterl.lazysodium.SodiumJava.<init>(SodiumJava.java:34)
    	at com.ql.wzwsdk.crypto.JavaCryptoLoader.load(JavaCryptoLoader.kt:10)
    	at com.ql.wzwsdk.crypto.Crypto.<clinit>(Crypto.kt:33)
    	at com.ql.wzwsdk.net.WzwSocketChannel.connectInternal$wzwSdk_debug(WzwSocketChannel.kt:148)
    	at com.ql.wzwsdk.net.WzwSocketChannel$connectInternal$1.invokeSuspend(Unknown Source:15)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@520c916, Dispatchers.IO]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.goterl.resourceloader.SharedLibraryLoader" on path: DexPathList[[zip file "/data/app/~~8DWEK0QWLR4qB6FO0waWnw==/com.ql.wzwsdkproject-ygCuGih0RRSvSjjkHdwkEA==/base.apk"],nativeLibraryDirectories=[/data/app/~~8DWEK0QWLR4qB6FO0waWnw==/com.ql.wzwsdkproject-ygCuGih0RRSvSjjkHdwkEA==/lib/arm64, /data/app/~~8DWEK0QWLR4qB6FO0waWnw==/com.ql.wzwsdkproject-ygCuGih0RRSvSjjkHdwkEA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by gurpreet-** [comment]
What version are you using? This lib depends on resource-loader which should be bundled together
