### ISSUE TITLE
Unable to load lazysodium with spring boot 3.2.2

### ISSUE THREAD

**Issue by ahazeltonNF** [terl/lazysodium-java#133]
Getting this exception during initialization:
```
2024-03-15T20:25:01.146920010Z Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
2024-03-15T20:25:01.146931299Z     at java.base/java.io.File.<init>(File.java:420)
2024-03-15T20:25:01.146933670Z     at com.goterl.resourceloader.ResourceLoader.urlToFile(ResourceLoader.java:588)
2024-03-15T20:25:01.146937295Z     at com.goterl.resourceloader.ResourceLoader.urlToFile(ResourceLoader.java:567)
2024-03-15T20:25:01.146948902Z     at com.goterl.resourceloader.ResourceLoader.extractFilesOrFoldersFromJar(ResourceLoader.java:227)
2024-03-15T20:25:01.146958719Z     at com.goterl.resourceloader.ResourceLoader.nestedExtract(ResourceLoader.java:174)
2024-03-15T20:25:01.147022290Z     at com.goterl.resourceloader.ResourceLoader.extractFromWithinAJarFile(ResourceLoader.java:98)
2024-03-15T20:25:01.147025093Z     at com.goterl.resourceloader.ResourceLoader.copyToTempDirectory(ResourceLoader.java:80)
2024-03-15T20:25:01.147026963Z     at com.goterl.resourceloader.SharedLibraryLoader.load(SharedLibraryLoader.java:53)
2024-03-15T20:25:01.147030026Z     at com.goterl.lazysodium.utils.LibraryLoader.loadBundledLibrary(LibraryLoader.java:134)
2024-03-15T20:25:01.147032942Z     at com.goterl.lazysodium.utils.LibraryLoader.loadLibrary(LibraryLoader.java:107)
2024-03-15T20:25:01.147037118Z     at com.goterl.lazysodium.SodiumJava.<init>(SodiumJava.java:34)
```

Worked correctly in SpringBoot 3.1.5

**Comment by sean-codevasp** [comment]
+1 here

**Comment by kolisko** [comment]
+1

**Comment by dovholuknf** [comment]
FYI - one of our engineers (Alan the one who filed this issue) submitted a patch to spring boot for this. you can see [the comment here if you wish](https://openziti.discourse.group/t/java-sdk-fat-jar-native-bindings-in-kubernetes/4699/3)...

> this is actually a bug with the resource loader that Spring Boot uses. The bug for that is here: [Spring Boot 3.2 nested jar references not supported · Issue #18 · terl/resource-loader · GitHub](https://github.com/terl/resource-loader/issues/18). Our patch has been merged but not release yet.

> Until the fix is released the workaround we're using internally is to unpack libsodium when the app is launched. This can be done via Spring Boot, and configured by the mvn or gradle spring boot plugins.

Gradle:
```
bootJar {
    requiresUnpack '**/lazysodium-java-*.jar'
}
```

Maven
```
<plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <requiresUnpack>
              <dependency>
                  <groupId>com.goterl</groupId>
                  <artifactId>lazysodium-java</artifactId>
              </dependency>
          </requiresUnpack>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>build-info</goal>
                <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
</plugin>
```

**Comment by umuterturk** [comment]
We have the same issue here, any suggestions?

**Comment by umuterturk** [comment]
this gradle kotlin task worked for us.
```
tasks.named<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    requiresUnpack("**/lazysodium-java-*.jar")
}

**Comment by gurpreet-** [comment]
Hi @umuterturk @sean-codevasp @kolisko,

Have you tried version 5.2.0. It contains commits that solve this error.

**Comment by kolisko** [comment]
@gurpreet-  I haven’t tried your fix. I fixed the issue in my fork a couple of months ago because I needed it quickly.

**Comment by sean-codevasp** [comment]
@gurpreet- yes., just updated the library. thx!
