### ISSUE TITLE
Make sure that the libsodium shared library can be used by more than 1 process

### ISSUE THREAD

**Issue by gurpreet-** [terl/lazysodium-java#53]
The problem is that if 2 processes are using Lazysodium, one of them will fail because not more than one process can access the shared library. 

```
Caused by: java.io.FileNotFoundException: C:\Users\mark\AppData\Local\Temp\lazysodium\libsodium.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at com.goterl.lazycode.lazysodium.utils.LibraryLoader.copyFromJarToTemp(LibraryLoader.java:244)
	at com.goterl.lazycode.lazysodium.utils.LibraryLoader.loadBundledLibrary(LibraryLoader.java:155)
```

I have recently changed lazysodium to load from the `lazysodium` folder that is not unique - this is highly likely where the error comes from. There are two ways we can solve this:

1. If we can copy the Lazysodium shared library into a special unique temp folder, then this bug will be resolved.
2. If we can make the Java loading code atomic across processes, this bug can be resolved.

**Comment by gurpreet-** [comment]
Resource loading out of a JAR is so terrible that I've created a dedicated library called [Resource Loader](https://github.com/libly/resource-loader) to solve this problem and abstract it in such a way that everyone can use it.

**Comment by gurpreet-** [comment]
Changes now incorporated in release `4.1.0`.
